### ISSUE TITLE
Using off-canvas no-undef  'Foundation' is not defined  

### ISSUE THREAD

**Issue by besnikh** [vue-foundation/vue-foundation#19]
Hi,
I am trying to use foundation off-canvas, not on all pages but on few pages but I can't seem to make it work.

I used exactly the same code as in demo version but when I add: 

```
mounted() {
    this.offCanvas = new Foundation.OffCanvas($('#offCanvas'));
  },
```

I get an error that foundation is underfined. 
` http://eslint.org/docs/rules/no-undef  'Foundation' is not defined  `
`http://eslint.org/docs/rules/no-undef  '$' is not defined`
main.js is unchanged: 
```
window.jQuery = jQuery;
window.$ = jQuery;

require('motion-ui');
require('what-input');
require('foundation-sites');
```

Is this supposed to happen or what should I do to include of-canvas in some pages. 

Thnx in advance,
Cheers

**Comment by grantcarthew** [comment]
That is just a eslint error @besnikh 

Have a look at this:
https://github.com/vue-foundation/vue-foundation/blob/master/.eslintrc.js#L41

That global section defines global variables so that eslint will understand the definition.

Essentially you are calling `new Foundation` and you have never defined what `Foundation` is. You don't need to define Foundation however you do need to tell eslint to shut up about it.
